/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { scene } = useGLTF("/Pakko_Model.glb", "/draco-gltf");
  return (
    <primitive object={scene} {...props}>
      <PerspectiveCamera position={[0, 0, 0]} fov={60} makeDefault />
    </primitive>
  );
}
useGLTF.preload("/landscape.glb");
