/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { scene } = useGLTF("/Pakko_Model.glb");
  return (
    <primitive object={scene} {...props}>
      <PerspectiveCamera position={[0, 0, 0]} fov={60} makeDefault />
    </primitive>
  );
}
useGLTF.preload("/landscape.glb");
